(()=>{
  const S = ()=>FrontierState;
  const esc = value => String(value ?? "").replace(/[&<>"']/g, c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const book = (left,right)=>`<section class="codex-stage"><div class="book"><div class="book-spread"><article class="book-page left">${left}<span class="page-number">•</span></article><article class="book-page right">${right}<span class="page-number">•</span></article></div></div></section>`;
  const lastLogDate=()=>{const last=S().logs.at(-1);if(!last)return null;const d=new Date(last.date);return Number.isNaN(d.getTime())?null:d};
  const elapsed=()=>{const d=lastLogDate();if(!d)return "No previous log has been recorded.";const hours=Math.max(1,Math.floor((Date.now()-d.getTime())/3600000));return `${hours} hour${hours===1?"":"s"} have elapsed since your previous log.`};
  const unfinished=()=>S().missions.filter(m=>!m.done).length;

  const renderThreshold=()=>`<section class="threshold-stage"><div class="threshold-stars"></div><div class="threshold-card"><div class="threshold-seal">✦</div><p class="threshold-kicker">A living record of becoming</p><h1>Project<br>Frontier</h1><p class="threshold-volume">${esc(FRONTIER_CAMPAIGN.book)}</p><div class="threshold-rule"></div><p class="threshold-owner">Property of ${esc(S().profile.name)}</p><p class="threshold-copy">Every action leaves a trace. Every chapter becomes history. The world does not reset. It continues.</p><button class="threshold-button" data-route="mission-control">Cross the Threshold</button><button class="threshold-secondary" data-route="contents">Open the Codex instead</button></div></section>`;

  const renderContents = ()=>book(
    `<p class="book-kicker">Contents</p><h1>The Frontier Codex</h1><p>Choose a page. Each section reflects a different part of the same expedition.</p><ul class="toc"><li><button data-route="chapter"><strong>Current Chapter</strong><span>01</span></button></li><li><button data-route="quests"><strong>Quest Journal</strong><span>02</span></button></li><li><button data-route="character"><strong>Character Sheet</strong><span>03</span></button></li><li><button data-route="archive"><strong>Expedition Archive</strong><span>04</span></button></li></ul>`,
    `<p class="book-kicker">Connected Realms</p><h2>Beyond the Book</h2><p>The Codex records direction. The remaining Realms interpret, support, and preserve the journey.</p><ul class="toc"><li><button data-route="mission-control"><strong>Mission Control</strong><span>MC</span></button></li><li><button data-route="log"><strong>Captain's Log</strong><span>CL</span></button></li><li><button data-route="observatory"><strong>Observatory</strong><span>OB</span></button></li></ul><div class="chapter-card"><h3>Main Quest</h3><p>${esc(FRONTIER_CAMPAIGN.mainQuest.text)}</p></div>`
  );
  const renderChapter = ()=>book(`<p class="book-kicker">${esc(FRONTIER_CAMPAIGN.chapter.number)}</p><h1>${esc(FRONTIER_CAMPAIGN.chapter.title)}</h1><p class="dropcap">${esc(FRONTIER_CAMPAIGN.chapter.summary)}</p><div class="chapter-card"><h3>Central Objective</h3><p>${esc(FRONTIER_CAMPAIGN.chapter.objective)}</p></div>`,`<p class="book-kicker">Conditions for advancement</p><h2>What This Chapter Asks</h2>${FRONTIER_CAMPAIGN.chapter.conditions.map((x,i)=>`<div class="quest-paper"><small>Milestone ${i+1}</small><p>${esc(x)}</p></div>`).join("")}<div class="book-actions"><button class="book-button" data-route="quests">Open Quest Journal</button></div>`);
  const questGroup = (title,key,xp)=>`<h3>${title}</h3>${S().quests[key].map(q=>`<div class="quest-paper ${q.done?"done":""}"><label><input type="checkbox" data-quest="${key}:${q.id}" ${q.done?"checked":""}><span><small>${esc(S().labels[q.cat])} · ${xp} XP</small>${esc(q.text)}</span></label></div>`).join("")}`;
  const renderQuests = ()=>book(`<p class="book-kicker">Quest Journal</p><h1>The Work Ahead</h1><div class="chapter-card"><h3>Main Quest</h3><p>${esc(FRONTIER_CAMPAIGN.mainQuest.text)}</p></div>${questGroup("Story Arcs","arcs",120)}`,`${questGroup("Side Quests","side",60)}${questGroup("Legendary Quests","legendary",250)}`);
  const renderCharacter = ()=>{const rows=S().cats.map(c=>{const xp=S().profile.xp[c],pct=xp%100;return `<tr><td><strong>${esc(S().labels[c])}</strong><div class="skill-meter"><span style="width:${pct}%"></span></div></td><td>Lv. ${Math.floor(xp/100)+1}</td><td>${xp} XP</td></tr>`}).join("");return book(`<p class="book-kicker">Character</p><h1>${esc(S().profile.name)}</h1><p>A multidisciplinary explorer developing practical competence, intellectual range, creative courage, and the stamina to continue.</p><div class="chapter-card"><h3>Current Title</h3><p>Engineer at the Threshold</p></div>`,`<h2>Disciplines</h2><table class="skill-table">${rows}</table>`)};
  const rings = ()=>S().cats.map(c=>{const xp=S().profile.xp[c];return `<div class="ring-row"><div class="ring" style="--pct:${xp%100};--ring-color:${S().colors[c]}"><span>${Math.floor(xp/100)+1}</span></div><div class="ring-info"><strong>${S().labels[c]}</strong><small>${xp} XP · ${100-(xp%100)} TO NEXT LEVEL</small></div></div>`}).join("");
  const missions = ()=>S().missions.map(m=>`<label class="mission-card"><input type="checkbox" data-mission="${m.id}" ${m.done?"checked":""}><span><span class="mission-meta">${esc(S().labels[m.category])}</span><span class="mission-label ${m.done?"done":""}">${esc(m.text)}</span></span><span class="mission-xp">+${m.xp}</span></label>`).join("");
  const renderControl = ()=>`<section class="control-stage"><div class="control-grid"><aside><section class="control-panel pad"><h2 class="panel-title">Discipline Status</h2><div class="ring-list">${rings()}</div></section><section class="control-panel pad"><h2 class="panel-title">Campaign Status</h2><div class="metric-grid"><div class="metric"><strong>${unfinished()}</strong><small>Active objectives</small></div><div class="metric"><strong>${S().missions.filter(m=>m.done).length}/${S().missions.length}</strong><small>Resolved today</small></div><div class="metric"><strong>${S().logs.length}</strong><small>Recorded logs</small></div></div></section></aside><div><section class="control-panel system-hero"><span class="eyebrow">Mission Control · ${esc(S().today)}</span><h1>Captain.</h1><div class="system-transmission"><p>Welcome back.</p><p>${esc(elapsed())}</p><p>${unfinished()} active objective${unfinished()===1?" remains":"s remain"}.</p><p>Further observation is required before new patterns can be reported.</p></div><div class="status-row"><span class="status-pill">SYSTEM: OPERATIONAL</span><span class="status-pill">CHAPTER: I</span><span class="status-pill">SYNC: LOCAL</span></div></section><section class="control-panel pad"><h2 class="panel-title">Daily Quests</h2><div id="mission-list">${missions()}</div><div class="action-row"><button class="ui-button" id="reroll">Reroll Unfinished</button><button class="ui-button primary" id="report-day">File Day Report</button></div><p id="report-status" class="muted"></p></section><section class="control-panel pad"><h2 class="panel-title">System Briefing</h2><div class="briefing"><h3>Hold the center.</h3><p>Complete one meaningful professional action, one act of personal maintenance, and one small action that keeps the wider expedition alive.</p><p class="confidence">Confidence: 74% · Based on current objectives and available local records.</p></div></section></div></div></section>`;
  const renderLog = ()=>`<section class="control-stage"><div class="view-wrap" style="padding-top:0"><section class="log-console"><div class="console-head"><span>CAPTAIN'S LOG</span><span>STARDATE ${new Date().getFullYear()}.${String(Math.ceil((new Date()-new Date(new Date().getFullYear(),0,0))/86400000)).padStart(3,"0")}</span></div><div class="field-grid"><div class="console-field"><label for="log-location">Location</label><input id="log-location" maxlength="100" placeholder="Philadelphia"></div><div class="console-field"><label for="log-status">Current state</label><select id="log-status"><option>Operational</option><option>Focused</option><option>Tired</option><option>Overwhelmed</option><option>Hopeful</option><option>Resting</option></select></div><div class="console-field full"><label for="log-report">Field report</label><textarea id="log-report" maxlength="5000" placeholder="What happened today? What mattered?"></textarea></div><div class="console-field"><label for="log-victory">Victory</label><input id="log-victory" maxlength="220" placeholder="One thing that went right"></div><div class="console-field"><label for="log-obstacle">Obstacle</label><input id="log-obstacle" maxlength="220" placeholder="One difficulty or unresolved thread"></div><div class="console-field full"><label for="log-tomorrow">Tomorrow's intention</label><input id="log-tomorrow" maxlength="220" placeholder="The next useful action"></div></div><div class="action-row"><button class="ui-button solid" id="save-log">Record Entry</button><button class="ui-button" id="export-data">Export Data</button></div></section><section class="control-panel pad" style="margin-top:18px"><h2 class="panel-title">Recent Logs</h2>${S().logs.slice().reverse().slice(0,5).map(x=>`<article class="archive-entry"><time>${esc(x.date)} · ${esc(x.location||"Location unrecorded")} · ${esc(x.status)}</time><p>${esc(x.report)}</p></article>`).join("")||'<p class="empty-state">No log entries yet.</p>'}</section></div></section>`;
  const renderArchive = ()=>book(`<p class="book-kicker">Expedition Archive</p><h1>What Has Been Lived</h1><p>The Archive gathers completed quests, day reports, and Captain's Log entries. Nothing meaningful disappears without the Captain's consent.</p><div class="book-actions"><button class="book-button" id="export-data-book">Export Archive</button></div>`,`<h2>Recent Entries</h2>${S().logs.slice().reverse().slice(0,8).map(x=>`<div class="quest-paper"><small>${esc(x.date)} · ${esc(x.location||"Unrecorded location")}</small><p>${esc(x.report)}</p></div>`).join("")||'<p>No entries have been bound into the archive yet.</p>'}`);

  const realm = (name,kicker,question,copy,items)=>`<section class="realm-stage realm-${name.toLowerCase()}"><div class="realm-shell"><p class="realm-kicker">${kicker}</p><h1>${name}</h1><p class="realm-question">${question}</p><p class="realm-copy">${copy}</p><div class="realm-cards">${items.map(([title,text])=>`<article><span>Pending system</span><h2>${title}</h2><p>${text}</p></article>`).join("")}</div></div></section>`;
  const renderSanctuary=()=>realm("Sanctuary","Recovery chamber","How do I recover?","This chamber remains quiet by design. It will hold breathing, gratitude, reflection, rest, and mindful rituals without turning recovery into another obligation.",[["Breathing","Guided and unguided breathing sessions."],["Reflection","Low-pressure prompts for processing the day."],["Gratitude","A private record of what sustained you."]]);
  const renderObservatory=()=>realm("Observatory","Long-range observation","How am I changing?","The stars are still gathering. Weekly, monthly, and long-term records will reveal patterns without diagnosis, judgment, or pressure.",[["Weekly Review","A calm summary of the previous seven days."],["Emotional Trends","Mood, energy, stress, confidence, and related observations."],["Pattern Reports","Correlations with explicit uncertainty and confidence levels."]]);
  const renderAtlas=()=>realm("Atlas","World mapping system","What does my world look like?","No territory has yet been fully charted. People, places, projects, organizations, skills, and connections will eventually form one navigable map.",[["People","Relationships and important context."],["Projects","Active efforts connected to quests and goals."],["Places","Locations, journeys, and meaningful environments."]]);
  const renderSettings=()=>realm("Settings","System configuration","How does Frontier serve me?","Settings will govern memory, notifications, appearance, data ownership, and the behavior of the Game Master.",[["Memory","Review, pin, archive, restore, or forget records."],["Notifications","Silence by default. Relevance earns interruption."],["Data & AI","Control exports, future cloud sync, and AI boundaries."]]);

  window.FrontierViews={threshold:renderThreshold,cover:renderThreshold,contents:renderContents,chapter:renderChapter,quests:renderQuests,character:renderCharacter,"mission-control":renderControl,log:renderLog,archive:renderArchive,sanctuary:renderSanctuary,observatory:renderObservatory,atlas:renderAtlas,settings:renderSettings};
})();
